export const lakes = [
  'Acton Island',
  'Antebellum',
  'Bala Retreat',
  'Barefoot Bungalow',
  'Bearhurst',
  'Belleview',
  'Bellevue',
  'Big Sound Lake House',
  'Birchwood',
  'Blissful Sands',
  'Blue Moon',
  'Blue My Mind',
  'Blueberry Point',
  'Brandy on the Rocks',
  'Breakwater',
  'Lake Muskoka',
  'Carpe Diem',
  'Cedar Ridge',
  'Cherry Island',
  'Chinook Lodge',
  'Cloud Nine',
  'Dacha Cottage',
  'Daydreams',
  'Deja Blue',
  'Dreamweaver',
  'Endless Summers',
  'Fabulous Lake Muskoka',
  'Falcon View',
  'Fly By Rosseau',
  'Harmony on Fume Lake',
  'Hemlock Lake House',
  "Heron's Landing",
  'Georgian Bay Beach House',
  'Go Big Joe',
  'Grandview Beach House',
  'Gregory Bay',
  'Hyannis Point North',
  'Indian River Respite',
  "It's A Wonderful Life",
  'Juddhaven',
  'Kahshe Lake',
  'Keewaydin Island Beaumaris',
  'Lakeside Charmer',
  'Lakhouse',
  'Lions Den',
  'Lorimer Lake',
  'Madison Point',
  'Magic in Grey Highlands',
  'Modern Kee',
  'Muskoka Family Fun',
  'Muskoka Reflections',
  'Muskoka Tall Trees',
  'Muskoka Wonderland',
  'Oastler Lake',
  'Oastler Ridge',
  'Post and Beam Lake Joe',
  "Priscilla's cottage",
  'Private Fleet',
  'Red Pines',
  'Lake Muskoka',
  "Robin's Nest",
  'Rocklands',
  'Rosecliff',
  'Sagamo',
  'Sanctuary',
  'Sand and Fun',
  'Sandy Shores',
  'Sapphire',
  'Seabreeze',
  'Second Wind',
  'Shore House',
  'Silver Dreams',
  'Simply Simcoe',
  'SkyPad',
  'Stewart Lake Retreat',
  'Sugar Shore',
  'Summit View',
  'Sunset Dreams',
  'Sunset Haven',
  'Sunset Lodge',
  'Sunshine Cove',
  'Tall Pines',
  'Taylor Island Lakehouse',
  'The Grand Lodge',
  'Three Mile Jewel',
  'Timbergrove',
  'Tranquility',
  'Uber Cool King W Condo',
  'Vantage Point',
  'Villa Lago',
  'Villa Lago Family Compound',
  'Villa Vista',
  "Walker's Point Beauty",
  'Westview',
  'Westwood',
  'Whispering Pines',
  'White Lily Cottage',
  'Wildflower Cottage',
  'Wildwood',
  'Winsome',
  'Woodlands',
  'Yellow Log Cabin',
  'Yorkville Pied a Terre',
];
